---
name: Build with BuildKit Cache
# simplest workflow possible

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

#NEW: ############################################################
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
#NEW: ############################################################
            
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
#NEW: ############################################################
          # builder: ${{ steps.buildx.outputs.name }}
#NEW: ############################################################
          push: ${{ github.event_name != 'pull_request' }}
          tags: bretfisher/allhands22:02
          cache-from: type=gha
          cache-to: type=gha,mode=max